---
env:
  contexts:
    - name: "Collector API"
      urls:
        - "http://localhost:8000"
      includePaths:
        - "http://localhost:8000.*"
      excludePaths: []
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true
    continueOnFailure: true

jobs:
  # Spider the main site - explore all accessible endpoints
  - type: spider
    parameters:
      context: "Collector API"
      url: "http://localhost:8000/"
      maxDuration: 2
      maxDepth: 5


  # Manually request API endpoints that spider won't discover
  # ZAP will scan these regardless of auth status (401/403 responses)
  - type: requestor
    parameters:
      user: ""
    requests:
      # Health endpoint
      - url: "http://localhost:8000/health"
        method: "GET"
      # Root endpoint
      - url: "http://localhost:8000/"
        method: "GET"
      # API endpoints
      - url: "http://localhost:8000/api/users"
        method: "GET"
      - url: "http://localhost:8000/api/articles"
        method: "GET"
      # ========================================
      # VULNERABLE TEST ENDPOINTS (for ZAP testing)
      # ========================================
      # XSS vulnerability test (URL encoded)
      - url: "http://localhost:8000/api/test/xss?name=%3Cscript%3Ealert(%27xss%27)%3C%2Fscript%3E"
        method: "GET"
      # Debug info exposure
      - url: "http://localhost:8000/api/test/debug"
        method: "GET"
      # SQL injection test (URL encoded)
      - url: "http://localhost:8000/api/test/search?q=%27%20OR%20%271%27%3D%271"
        method: "GET"
      # Open redirect test
      - url: "http://localhost:8000/api/test/redirect?url=http://evil.com"
        method: "GET"
      # Missing security headers
      - url: "http://localhost:8000/api/test/insecure"
        method: "GET"
      # Sensitive error messages
      - url: "http://localhost:8000/api/test/error"
        method: "GET"
      - url: "http://localhost:8000/api/test/error?id=1"
        method: "GET"


  # Wait for passive scanning to complete
  - type: passiveScan-wait
    parameters:
      maxDuration: 5


  # Active scan for common vulnerabilities
  - type: activeScan
    parameters:
      context: "Collector API"
      maxRuleDurationInMins: 1
      maxScanDurationInMins: 5


  # Generate reports in the reports directory
  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/reports"
      reportFile: "zap-report"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk/reports"
      reportFile: "zap-report"

  - type: report
    parameters:
      template: "traditional-md"
      reportDir: "/zap/wrk/reports"
      reportFile: "zap-report"
