{
 "title": "Micro service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Taux de disponibilité (SLA)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_router_requests_total{code!~\"5..\"}[5m])) / sum(rate(traefik_router_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreurs 5xx",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_router_requests_total{code=~\"5..\"}[5m])) or vector(0)) \r\n/ \r\nsum(rate(traefik_router_requests_total[5m])) \r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P99",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket[5m])) by (service, le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requêtes en cours",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_router_requests_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic Global (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(traefik_router_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Codes HTTP par seconde (Statut)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(traefik_router_requests_total[1m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}